source 'https://github.com/CocoaPods/Specs.git'
source 'https://git.yy.com/opensource/ios_team/Spec.git'
source 'https://git.yy.com/ci_team/Specs.git'
source 'https://git.yy.com/midwares/modular/athservicespecs-ios.git'

platform :ios, '9.0'
inhibit_all_warnings!

target 'YYFlutterSDK_Example' do
    #pod 'FlutterApi', :git => 'https://github.com/673697831/YYFlutterModule.git'
  pod 'FlutterApi', :path => '../../YYFlutterModule'
  pod 'YYFlutterSDK', :path => '../'

  target 'YYFlutterSDK_Tests' do
    inherit! :search_paths

    
  end
end
