source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'YYFlutterSDK_Example' do
  pod 'YYFlutterSDK', :path => '../'

  target 'YYFlutterSDK_Tests' do
    inherit! :search_paths

    
  end
end
