source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
inhibit_all_warnings!

target 'YYFlutterSDK_Example' do
  pod 'YYFlutterSDK', :path => '../'

  target 'YYFlutterSDK_Tests' do
    inherit! :search_paths

    
  end
end

flutter_application_path = '../flutter_module'
eval(File.read(File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')), binding)
